Traceback (most recent call last):
  File "../../parser.py", line 77, in <module>
    main()
  File "../../parser.py", line 73, in main
    parser.parse()
  File "/usr/local/lib/python3.8/dist-packages/lab/parser.py", line 216, in parse
    file_parser.apply_functions(self.props)
  File "/usr/local/lib/python3.8/dist-packages/lab/parser.py", line 115, in apply_functions
    function(self.content, props)
  File "../../parser.py", line 18, in find_all_occurences
    props[name] = [type(m) for m in matches]
  File "../../parser.py", line 18, in <listcomp>
    props[name] = [type(m) for m in matches]
TypeError: 'list' object is not callable
